---
- hosts: all
  become: yes

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - include: tasks/pre-tasks.yml

  roles:
    - { role: sysadmin.common, tags: ['common'] }
    - { role: sysadmin.nginx-proxy, tags: ['nginx'] }
    
  tasks:
    #- include: tasks/post-tasks.yml