---
- hosts: all
  become: yes

  vars_files:
    - group_vars/all.yml

  #pre_tasks:
  #  - include: tasks/pre-tasks.yml

  roles:
    - { role: sysadmin.common, tags: ['common'] }
    - { role: sysadmin.nginx, tags: ['nginx'] }
    - { role: sysadmin.php7x, tags: ['php'] }
    - { role: geerlingguy.composer, tags: ['composer'] }
    - { role: geerlingguy.drush, tags: ['drush'] }
    - { role: sysadmin.supervisord, tags: ['supervisord'] }    

  tasks:
    #- include: tasks/post-tasks.yml