version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - mysql:mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin