---
# tasks file for roles/sysadmin.nginx
# Ref: https://linuxize.com/post/how-to-install-nginx-on-ubuntu-16-04/
- name: PHP | Install Ondrej PHP PPA
  apt_repository: repo='ppa:nginx/stable' update_cache=yes

- name: Install nginx
  apt:
    name: "{{ item }}"
  with_items:
    - nginx

- name: Remove default nginx
  file:
    path: "/etc/nginx/sites-available/default"
    state: absent
  when: nginx_remove_default_vhost == true

# Remove unused vhosts
- name: nginx_remove_sites
  file:
    path: '/etc/nginx/sites-enabled/{{ item }}.conf'
    state: absent
  with_items: "{{ nginx_remove_sites }}"

# nginx.conf
- name: nginx.conf
  template:
    src: 'templates/{{ item }}.conf'
    dest: '/etc/nginx/{{ item }}.conf'
    force: yes
  with_items: "{{ nginx_conf }}"

# with_items is a list of name in templates
- name: nginx_sites
  template:
    src: 'templates/{{ item }}.conf.j2'
    dest: '/etc/nginx/sites-enabled/{{ item }}.conf'
    force: yes
  with_items: "{{ nginx_sites }}"