---
# tasks file for roles/sysadmin.nginx
# Ref: https://linuxize.com/post/how-to-install-nginx-on-ubuntu-16-04/
- name: PHP | Install Ondrej PHP PPA
  apt_repository: repo='ppa:nginx/stable' update_cache=yes

- name: Install nginx
  apt:
    name: "{{ item }}"
  with_items:
    - nginx

- name: Remove default nginx
  file:
    path: "/etc/nginx/sites-available/default"
    state: absent

- name: nginx.conf
  file:
    path: '/etc/nginx/sites-enabled/{{ item }}.conf'
    state: absent
  with_items:
    - vhost-01
    - vhost-02

# Remove unused vhosts
- name: Remove unsued vhosts
  file:
    path: '/etc/nginx/sites-enabled/{{ item }}.conf'
    state: absent
  with_items:
    - vhost-01
    - vhost-02

- name: nginx.conf
  template:
    src: 'templates/{{ item }}.conf'
    dest: '/etc/nginx/{{ item }}.conf'
    force: yes
  with_items:
    - nginx

# with_items is a list of name in templates
- name: Configure vhosts
  template:
    src: 'templates/{{ item }}.conf.j2'
    dest: '/etc/nginx/sites-enabled/{{ item }}.conf'
    force: yes
  with_items:
    - demo.com