---
# tasks file for roles/sysadmin.nginx
# Ref: https://linuxize.com/post/how-to-install-nginx-on-ubuntu-16-04/
- name: PHP | Install Ondrej PHP PPA
  apt_repository: repo='ppa:nginx/stable' update_cache=yes

- name: Install nginx
  apt: name=nginx state=latest

- name: Remove default nginx
  file:
    path: "/etc/nginx/sites-available/default"
    state: absent
  when: nginx_remove_default_vhost == true

# nginx.conf
- name: nginx.conf
  template:
    src: 'templates/{{ item }}.conf'
    dest: '/etc/nginx/{{ item }}.conf'
    force: yes
  with_items: "{{ nginx_conf }}"

# remove unused vhosts
- name: nginx_remove_sites
  file:
    path: '/etc/nginx/sites-enabled/{{ item }}.conf'
    state: absent
  with_items: "{{ nginx_remove_sites }}"

# with_items is a list of name in templates
- name: nginx_sites
  template:
    src: 'templates/nginx-http.conf.j2'
    dest: '/etc/nginx/sites-enabled/{{ item }}.conf'
    force: yes
  with_items: "{{ nginx_sites }}"

- name: nginx_sites https
  template:
    src: 'templates/nginx-https.conf.j2'
    dest: '/etc/nginx/sites-enabled/{{ item }}.conf'
    force: yes
  with_items: "{{ nginx_sites }}"

# Let's encrypt
- name: install letsencrypt
  apt: name=letsencrypt state=latest

- name: create letsencrypt directory
  file: name=/var/www/letsencrypt state=directory

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} && service nginx reload
# Let's encrypt