apiVersion: v1
kind: Service
metadata:
  name: drupal-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: drupal-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-app
  template:
    metadata:
      labels:
        app: drupal-app
    spec:
      containers:
      - name: drupal-app
        image: gcr.io/k8s-test-218207/drupal-app:v1.0
        envFrom:
          - configMapRef:
              name: env-config
        #  - secretRef:
        #      name: env-secret
        ports:
        - containerPort: 80
